export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const MESSAGING_ERROR = "MESSAGING_ERROR";
export const START_LOADING_MESSAGES = "START_LOADING_MESSAGES";
