export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const MARK_ALL_NOTIFICATIONS_READ = "MARK_ALL_NOTIFICATIONS_READ";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
